// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNadvI-BPNLwWBCl7VUVa9LsTTBgmqbs',
    appId: '1:256429737542:web:157ab42f667afba6876c47',
    messagingSenderId: '256429737542',
    projectId: 'flutter-apps-4bf2d',
    authDomain: 'flutter-apps-4bf2d.firebaseapp.com',
    storageBucket: 'flutter-apps-4bf2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAM9-jjIIy9kh_mn5TFCQU3kPVautaTU',
    appId: '1:256429737542:android:f5d1ecdfad0d748a876c47',
    messagingSenderId: '256429737542',
    projectId: 'flutter-apps-4bf2d',
    storageBucket: 'flutter-apps-4bf2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRY8zSSTRj4usw0M8dHKilxSFFeBJkJwM',
    appId: '1:256429737542:ios:c4b5a06ba4bf7b05876c47',
    messagingSenderId: '256429737542',
    projectId: 'flutter-apps-4bf2d',
    storageBucket: 'flutter-apps-4bf2d.appspot.com',
    iosBundleId: 'com.example.mobileAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRY8zSSTRj4usw0M8dHKilxSFFeBJkJwM',
    appId: '1:256429737542:ios:c4b5a06ba4bf7b05876c47',
    messagingSenderId: '256429737542',
    projectId: 'flutter-apps-4bf2d',
    storageBucket: 'flutter-apps-4bf2d.appspot.com',
    iosBundleId: 'com.example.mobileAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuNadvI-BPNLwWBCl7VUVa9LsTTBgmqbs',
    appId: '1:256429737542:web:59dab7f57cb2b5fb876c47',
    messagingSenderId: '256429737542',
    projectId: 'flutter-apps-4bf2d',
    authDomain: 'flutter-apps-4bf2d.firebaseapp.com',
    storageBucket: 'flutter-apps-4bf2d.appspot.com',
  );
}
